services:
  app:
    image: hannastigland/webservices:1
    depends_on:
      - mysql
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/webserviceslabb2
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_JPA_PLATFORM: mysql
    restart: on-failure

  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
      MYSQL_USER: myuser
      MYSQL_DATABASE: webserviceslabb2
    ports:
      - '3306:3306'